### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by pixelass** [FormidableLabs/spectacle-boilerplate#26]
When I run `npm start` i get the following error

```bash
ERROR in ./index.js
Module build failed: ReferenceError: 
Unknown plugin "react-transform" specified in "base.env.development" at 0...
```

**Comment by chihhunglin** [comment]
@pixelass need react-transform package

please reference to https://github.com/gaearon/react-transform-hmr#installation

**Comment by pixelass** [comment]
should be in package.json. it's missing
