### ISSUE TITLE
simple two columns, full height slide

### ISSUE THREAD

**Issue by nekapoor** [FormidableLabs/spectacle-boilerplate#29]
Hello!

I'm sorry if this is obvious, but is there an easy way to create a slide that has two full-height columns that take up the entire width (each 50% of the screen)?  

Thank you!

**Comment by kenwheeler** [comment]
You'll probably want to add a className to your slide content element and position it absolutely. Then, you can use <Layout><Fill/><Fill/></Layout> to achieve that.
