### ISSUE TITLE
Does't not work out of the box

### ISSUE THREAD

**Issue by Sly321** [FormidableLabs/spectacle-boilerplate#69]
I did a `git clone`
`yarn`
`yarn start`

and get this error on `localhost:3000 

`TypeError: Cannot read property 'props' of undefined
Manager._renderSlide
webpack:///node_modules/spectacle/es/components/manager.js:752
Manager.render
webpack:///node_modules/spectacle/es/components/manager.js:838
finishClassComponent
webpack:///node_modules/react-dom/cjs/react-dom.development.js:10249
updateClassComponent
webpack:///node_modules/react-dom/cjs/react-dom.development.js:10226
beginWork
webpack:///node_modules/react-dom/cjs/react-dom.development.js:10605
performUnitOfWork
webpack:///node_modules/react-dom/cjs/react-dom.development.js:12573
workLoop
webpack:///node_modules/react-dom/cjs/react-dom.development.js:12682
HTMLUnknownElement.callCallback
webpack:///node_modules/react-dom/cjs/react-dom.development.js:1299
Object.invokeGuardedCallbackDev
webpack:///node_modules/react-dom/cjs/react-dom.development.js:1338
invokeGuardedCallback
webpack:///node_modules/react-dom/cjs/react-dom.development.js:1195`

On Ubuntu 18.04.1 LTS 64bit with Google Chrome Version 69.0.3497.100

**Comment by ebrillhart** [comment]
This should be working after a recent PR merge. Please reopen with new details if you're still having trouble. Thanks!
