### ISSUE TITLE
Updating Spectacle boilerplate in existing project

### ISSUE THREAD

**Issue by karlhorky** [FormidableLabs/spectacle-boilerplate#71]
### Question

Hi there! First of all, thanks for all the effort in creating Spectacle and this boilerplate. It's a great way to create presentations and has inspired a number of great followup libraries too!

The issue that I currently have is that I would like to update an existing project with the new dependencies and updates that have been made to the boilerplate (I'm doing this to fix security issues in `webpack-dev-server` as explained in yarnpkg/yarn#6909).

I would like to apply all changes since I first cloned the boilerplate. Unfortunately, I removed all git history from the boilerplate, so pulling from upstream will probably not work.

### Background Info/Attempts

I could just try applying the patch for the one change that I really want (#68), but this may not work in case other files have been updated before that change...

I could also just re-clone the boilerplate and then copy over my presentation files and fix any problems, but this would lose my git history.

If there is no recommended way for doing this, I suppose I will just try to apply the changes from the boilerplate manually.

**Comment by ebrillhart** [comment]
Hm this is a good question! I'd say probably the best way to handle it would be to copy over the package.json from the current version of Spectacle Boilerplate to your project - that should handle all of the necessary dependency updates, and then you can adjust/fix existing work as needed.

**Comment by karlhorky** [comment]
Hm, yeah updating just the `package.jaon` was not enough, I needed to manually update almost every file in the root.

Didn't take so long (about 30 minutes), but an automated update / CRA-style package instead of a copied boilerplate would be cool for the future.

Thanks for the answer though!
